HTTP_PROXY=http://127.0.0.1:${PROXY_PORT}
HTTPS_PROXY=http://127.0.0.1:${PROXY_PORT}
http_proxy=http://127.0.0.1:${PROXY_PORT}
https_proxy=http://127.0.0.1:${PROXY_PORT}
NO_PROXY=localhost,127.0.0.1,::1,*.aigcic.com,gitlab-sw.aigcic.com,192.168.0.0/16,172.16.0.0/12,10.0.0.0/8
no_proxy=localhost,127.0.0.1,::1,*.aigcic.com,gitlab-sw.aigcic.com,192.168.0.0/16,172.16.0.0/12,10.0.0.0/8
